apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: efs-storage-claim
    namespace: default
    resourceVersion: "98903"
    uid: 1272d0b4-d603-4201-abc0-2bb01cc6cf2d
  csi:
    driver: efs.csi.aws.com
    volumeHandle: EFS_VOLUME_ID
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  volumeMode: Filesystem
