injector:
  enabled: false
ui:
  enabled: true
server:
  affinity: ""
  dataStorage:
    enabled: false
    storageClass: "gp2"
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "file" {
        path = "/vault/data"
      }
  ha:
    enabled: false